[SessionMiddleware]
SessionService = "session"
VerifySlot = "verifyToken"
WhiteList = ["v1:login,checkLogin"]
InUserField = 'User'
InTokenField = 'Token'
InAddressField = 'IP'
InAgentField = "Agent"
OutUserField = 'user'
OutTokenField = 'token'
OutAddressField = 'ip'
OutAgentField = 'agent'