LogFileName = 'sa.log'
LogOutputs = ['file', 'console']
Version = '1.0'
Debug = true


[Server]
MaxProcs = 1

[APIGateway]
BreakerLimitApi = true
BreakerLimitIP = true
BreakerLimitUser = true
BreakerRequestTimeout = 10
BreakerDashboard = true
BreakerEnabled = true
BreakerMaxConcurrentRequest = 10
BreakerRequestVolumeThreshold = 10
BreakerSleepWindow = 10
BreakerErrorPercentThreshold = 10
AddressField = 'IP'
UserField = 'User'